### ISSUE TITLE
Sessions not starting

### ISSUE THREAD

**Issue by anthonybaldwin** [aerokube/moon#73]
I installed Moon to a new cluster and am having issues running the same tests that were working before—without any changes AFAICT. When I click to view the session w/in selenoid-ui, it's stuck and displays the log below.

This is what I see via selenoid-ui:
```
anthony@baldwin:~/Repos/moon-deploy$ ktl logs chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2 browser -n moon
Waiting xvfb...

 --- x11vnc loop: 1 ---

Starting ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac) on port 4444
All remote connections are allowed. Use a whitelist instead!
 --- x11vnc loop: waiting for: 40

PORT=5900
```

Moon logs:
```
anthony@baldwin:~/Repos/moon-deploy$ ktl logs moon-574754684f-6cf59 moon -n moon
2018/10/12 04:28:45 [INIT] [Guest access is supported as user "browsers"]
2018/10/12 04:28:45 [INIT] [S3 storage is not configured: content upload is unavailable]
2018/10/12 04:28:45 [INIT] [Using default Moon images: failed to fetch moon-config map: configmaps "moon-config" not found]
2018/10/12 04:28:45 [INIT] [Using aerokube/logger:latest image as logger]
2018/10/12 04:28:45 [INIT] [Using aerokube/moon-video-recorder:latest image as videoRecorder]
2018/10/12 04:28:45 [INIT] [Using aerokube/defender:latest image as defender]
2018/10/12 04:28:45 [INIT] [Listening on :4444]
2018/10/12 04:28:45 [INIT] [Found license for "xxx" allowing 50 simultaneous browser sessions (valid from 1970-01-01T00:00:00Z until 2019-03-01T00:00:00Z)]
2018/10/12 04:28:45 [INIT] [Moon is now working properly]

anthony@baldwin:~/Repos/moon-deploy$ ktl logs moon-574754684f-b5ldc moon -n moon
2018/10/12 04:28:49 [INIT] [Guest access is supported as user "browsers"]
2018/10/12 04:28:49 [INIT] [S3 storage is not configured: content upload is unavailable]
2018/10/12 04:28:49 [INIT] [Using default Moon images: failed to fetch moon-config map: configmaps "moon-config" not found]
2018/10/12 04:28:49 [INIT] [Using aerokube/moon-video-recorder:latest image as videoRecorder]
2018/10/12 04:28:49 [INIT] [Using aerokube/defender:latest image as defender]
2018/10/12 04:28:49 [INIT] [Using aerokube/logger:latest image as logger]
2018/10/12 04:28:49 [INIT] [Listening on :4444]
2018/10/12 04:28:49 [INIT] [Found license for "xxx" allowing 50 simultaneous browser sessions (valid from 1970-01-01T00:00:00Z until 2019-03-01T00:00:00Z)]
2018/10/12 04:28:49 [INIT] [Moon is now working properly]
2018/10/12 04:35:17 [CREATING_POD] [browsers] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2]
2018/10/12 04:35:17 [CREATING_SERVICE] [browsers] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2]
2018/10/12 04:35:17 [SERVICE_CREATED] [browsers] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2] [0.68s]
2018/10/12 04:35:17 [POD_CREATED] [browsers] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2] [0.70s]
2018/10/12 04:35:17 [AWAITING_SERVICE] [browsers] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2]
```
Moon api logs:
```
anthony@baldwin:~/Repos/moon-deploy$ ktl logs moon-574754684f-6cf59 moon-api -n moon
2018/10/12 04:28:45 [INIT] [Found license for "xxx"]
2018/10/12 04:28:45 [INIT] [Listening on :8888]
2018/10/12 04:29:00 [STATUS_REQUEST] [::1]
2018/10/12 04:29:05 [STATUS_REQUEST] [::1]
2018/10/12 04:29:10 [STATUS_REQUEST] [::1]
2018/10/12 04:29:15 [STATUS_REQUEST] [::1]
2018/10/12 04:30:25 [LOGS] [10.128.0.4] [chrome-69-0-60acbe04-e4a6-4217-a788-ab835937ad4b]
2018/10/12 04:32:10 [LOGS_CLIENT_DISCONNECTED] [10.128.0.4] [chrome-69-0-60acbe04-e4a6-4217-a788-ab835937ad4b]
2018/10/12 04:42:38 [LOGS] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2]
2018/10/12 04:42:38 [VNC_SESSION] [10.128.0.7] [chrome-69-0-953027c8-c895-4ba5-9c83-3b84c64f9ad2]
2018/10/12 04:43:15 [STATUS_REQUEST] [::1]
2018/10/12 04:43:20 [STATUS_REQUEST] [::1]
2018/10/12 04:43:25 [STATUS_REQUEST] [::1]
2018/10/12 04:43:30 [STATUS_REQUEST] [::1]
2018/10/12 04:43:35 [STATUS_REQUEST] [::1]
2018/10/12 04:43:40 [STATUS_REQUEST] [::1]
2018/10/12 04:43:45 [STATUS_REQUEST] [::1]
2018/10/12 04:43:50 [STATUS_REQUEST] [::1]
2018/10/12 04:43:55 [STATUS_REQUEST] [::1]
2018/10/12 04:44:00 [STATUS_REQUEST] [::1]
2018/10/12 04:44:05 [STATUS_REQUEST] [::1]
2018/10/12 04:44:10 [STATUS_REQUEST] [::1]
2018/10/12 04:44:15 [STATUS_REQUEST] [::1]
2018/10/12 04:44:20 [STATUS_REQUEST] [::1]
2018/10/12 04:44:25 [STATUS_REQUEST] [::1]
2018/10/12 04:44:30 [STATUS_REQUEST] [::1]
2018/10/12 04:44:35 [STATUS_REQUEST] [::1]
2018/10/12 04:44:40 [STATUS_REQUEST] [::1]
2018/10/12 04:44:45 [STATUS_REQUEST] [::1]
2018/10/12 04:44:50 [STATUS_REQUEST] [::1]
2018/10/12 04:44:55 [STATUS_REQUEST] [::1]
2018/10/12 04:45:00 [STATUS_REQUEST] [::1]
2018/10/12 04:45:05 [STATUS_REQUEST] [::1]
2018/10/12 04:45:10 [STATUS_REQUEST] [::1]
2018/10/12 04:45:15 [STATUS_REQUEST] [::1]
2018/10/12 04:45:20 [STATUS_REQUEST] [::1]
2018/10/12 04:45:25 [STATUS_REQUEST] [::1]

anthony@baldwin:~/Repos/moon-deploy$ ktl logs moon-574754684f-nmvg5 moon-api -n moon
2018/10/12 04:43:10 [INIT] [Found license for "xxx"]
2018/10/12 04:43:10 [INIT] [Listening on :8888]
```

Eventually, my test just times out:

```
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: '17MB-21F-1089.local', ip: '172.29.17.95', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_161'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.xxx.app.tools.TestBase.getChromeDriver(TestBase.java:237)
	at com.xxx.app.tools.TestBase.setupDriver(TestBase.java:103)
	at com.xxx.app.tools.TestBase._beforeClass(TestBase.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: unexpected end of stream on Connection{35.xxx.xxx.xxx:4444, proxy=DIRECT hostAddress=/35.xxx.xxx.xxx:4444 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	... 19 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 39 more
```

I'm seeing the same thing with the Selenoid demo test.

**Comment by vania-pooh** [comment]
@anthonybaldwin is it `aerokube/moon:latest` image or a release?

**Comment by anthonybaldwin** [comment]
@vania-pooh release: `aerokube/moon:1.1.7`

Edit: I'm using the default moon.yaml file, and have only increased the # of allowed pods to 52, plus added my license key.

**Comment by anthonybaldwin** [comment]
This appears to be fixed with `aerokube/moon:latest`.

**Comment by vania-pooh** [comment]
@anthonybaldwin yesterday we released `aerokube/moon:1.1.8`. Please check whether it works.

**Comment by neofreko** [comment]
I still see this issue even in 1.2.0. With 1.1.6, a browser session is immediately started after we send the request. Later version will only show blank screen until timing out.

**Comment by vania-pooh** [comment]
@neofreko could you check Moon logs or do `kubectl describe po <some-browser-pod> -n moon` and show the output here? I think you could have insufficient resources in Kubernetes.

**Comment by jmieleiii** [comment]
Hi @vania-pooh, we are seeing the same exact issue. We are running `aerokube/moon:latest`. We can sometimes get around this by adding a retry to the driver initialization, but often times it will exhaust the retry limit (5) and ultimately fail

Running your command above on some browser pod:
```
$ kubectl describe po chrome-71-0-ee51f7f0-d5eb-4bad-95f6-601471a389e7
Name:               chrome-71-0-ee51f7f0-d5eb-4bad-95f6-601471a389e7
Namespace:          selenium-test
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=chrome-71-0-ee51f7f0-d5eb-4bad-95f6-601471a389e7
                    browserName=chrome
                    enableVNC=true
                    moon=browser
                    quota=browsers
                    screenResolution=1920x1080x24
                    version=71.0
Annotations:        name=test rider can not buy another starter 3 pack series
                    timeZone=UTC
Status:             Pending
IP:
Containers:
  browser:
    Image:       selenoid/vnc_chrome:71.0
    Ports:       4444/TCP, 5900/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     500m
      memory:  512Mi
    Environment:
      TZ:                 UTC
      SCREEN_RESOLUTION:  1920x1080x24
      ENABLE_VNC:         true
      ENABLE_VIDEO:       false
    Mounts:
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from -- (ro)
  defender:
    Image:      aerokube/defender:latest
    Port:       4545/TCP
    Host Port:  0/TCP
    Command:
      /defender
      -proxy-url
      http://localhost:4444
      -session-timeout
      1m0s
    Limits:
      cpu:     250m
      memory:  128Mi
    Requests:
      cpu:        250m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from d-- (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  dshm:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  --:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  --
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Warning  FailedScheduling   2m (x281 over 7m)  default-scheduler   0/18 nodes are available: 18 Insufficient cpu.
  Normal   NotTriggerScaleUp  1m (x26 over 7m)   cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

**Comment by vania-pooh** [comment]
@jmieleiii you have insufficient resources - it is clearly stated in your output.
```
0/18 nodes are available: 18 Insufficient cpu.
```

**Comment by jmieleiii** [comment]
I re-provisioned the grid and tried running a small number of browsers (10). Some tests completed but once again tests eventually started timing out and 10 pods are now "stuck". However none of these pods include the resource errors found above.

One of the moon logs for a moon pod includes:
```
kubectl logs moon-6f54d98c6c-n8sqk moon
2019/01/16 03:32:02 [PROXY_ERROR] [unknown] [24.34.18.218, 35.241.31.175, 10.168.0.56, 10.169.1.6] [DELETE http://chrome-71-0-51a1e0f9-c3cf-462b-85cb-974867cdae75:4545/session/chrome-71-0-51a1e0f9-c3cf-462b-85cb-974867cdae75] [context canceled]
```

And the describe for that pod doesn't indicate any errors:
```
$ kubectl describe po chrome-71-0-51a1e0f9-c3cf-462b-85cb-974867cdae75
Events:
  Type    Reason     Age   From                                                Message
  ----    ------     ----  ----                                                -------
  Normal  Scheduled  11m   default-scheduler                                   Successfully assigned selenium-/chrome-71-0-51a1e0f9-c3cf-462b-85cb-974867cdae75 to gke-east1-cluster-main-pool-35e174c9-z0rq
  Normal  Pulled     11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Container image "selenoid/vnc_chrome:71.0" already present on machine
  Normal  Created    11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Created container
  Normal  Started    11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Started container
  Normal  Pulling    11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  pulling image "aerokube/defender:latest"
  Normal  Pulled     11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Successfully pulled image "aerokube/defender:latest"
  Normal  Created    11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Created container
  Normal  Started    11m   kubelet, gke-east1-cluster-main-pool-35e174c9-z0rq  Started container
```

**Comment by jmieleiii** [comment]
@vania-pooh  I think I've narrowed a lot of failure down to insufficient resources. Is there any documentation on recommended cluster size and machine types? i.e. if we want to be able to run 100 instance concurrently what kind of specs should we aim for?

**Comment by vania-pooh** [comment]
@jmieleiii by default every Kubernetes node consumes at least 0.5 CPU and 512 Mb RAM for service purposes, then every Moon pod by default consumes 1 CPU + 1 Gb RAM (or 2 CPU + 2Gb with video recording). All these values except Kubernetes itself can be adjusted in Moon settings - by these are the default to calculate number of nodes.

**Comment by vania-pooh** [comment]
Closing because of inactivity. Feel free to reopen if still having questions.
